# baseURL = 'http://localhost:1313/'
baseURL = 'https://github.com/yota5555yota-lab/MaterialsStrength-website.git'

title = '材料強度学研究室'

theme = "PaperMod"

defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true
disableDefaultLanguageRedirect = false

[languages]

  # ===== 日本語 =====
  [languages.ja]
    languageName = "日本語"
    weight = 1
    contentDir = "content/ja"

    [[languages.ja.menu.main]]
      name = "研究室紹介"
      url = "mission/"
      weight = 1

    [[languages.ja.menu.main]]
      name = "メンバー"
      url = "members/"
      weight = 2

    [[languages.ja.menu.main]]
      name = "業績"
      url = "publications/"
      weight = 3

    [[languages.ja.menu.main]]
      name = "アクセス"
      url = "access/"
      weight = 4

    [[languages.ja.menu.main]]
      name = "お問い合わせ"
      url = "contact/"
      weight = 5


  # ===== 英語 =====
  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"

    [[languages.en.menu.main]]
      name = "Mission"
      url = "mission/"
      weight = 1

    [[languages.en.menu.main]]
      name = "Members"
      url = "members/"
      weight = 2

    [[languages.en.menu.main]]
      name = "Publications"
      url = "publications/"
      weight = 3

    [[languages.en.menu.main]]
      name = "Access"
      url = "access/"
      weight = 4

    [[languages.en.menu.main]]
      name = "Contact"
      url = "contact/"
      weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  label = { text = "材料強度学研究室", icon = "/images/logo.png", iconHeight = 35 }
